---
params:
  year: 2018
title:  "`r params$year`年度資源評価"
output:
  bookdown::pdf_document2:
   latex_engine: xelatex
   toc: no
highlight: "zenburn"
mainfont: ipaexm.ttf
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_knit$set(eval.after = "fig.cap")
```

```{r setup, include = FALSE}
library("stockdocr")
library("knitr")
library("ggvis")
devtools::load_all()
yr_newest_catch <- params$year - 1
years <- get_year_from_vpa_result(res_vpa)
```
# 資源の状況
資源量は`r yr_newest_catch`年に
`r b(res_vpa, year = yr_newest_catch, unit = "kton")`トンまで急増した

漁獲率は`r yr_newest_catch`年には
`r harvest_rate(res_vpa, year = yr_newest_catch)`%となった

加入量は
`r yr_newest_catch`年には`r r(res_vpa, year = yr_newest_catch)`尾となった

親魚量は
`r yr_newest_catch`年に
`r ssb(res_vpa, year = yr_newest_catch, unit = "kton")`トンとなった

```{r great, echo = FALSE}
table_foo(res_vpa, yr_newest_catch, caption = paste0("My great table in ", yr_newest_catch))
```
表\@ref(tab:great)を見てください

```{r catch, fig.cap = paste0("Annual variation in Foo catch during", min(years), "--",  yr_newest_catch), fig.width = 5, echo = FALSE}
plot_vpa(res_vpa, "ssb") +
  ggplot2::ylab("great y axis")
```

図\@ref(fig:catch)を見てください
